language : node_js
node_js :
    - "0.12"
    - "4"
    - "5"
    - "6"
python:
    - "2.7"
before_install:
    - sudo apt-get update -y -qq
    - sudo apt-get install -y graphviz plotutils imagemagick
    - sudo pip install image scruffy
    - npm install -g npm
before_script :
    - npm install -g grunt-cli
