sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphviz
      - plotutils
      - imagemagick
      - librsvg2-bin
      - build-essential
      - g++-4.8
env:
  - CXX=g++-4.8
node_js:
  - '8'
  - '6'
  - '4'
python:
  - "2.7"
before_install:
  - pip install --user -U pip
  - pip install --user image scruffy
  - npm install -g npm
before_script:
  - npm install -g grunt-cli
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
